In [ ]:
import pandas as pd 
import numpy as np 
import requests
import json
import ast

In [5]:
text_data=pd.read_csv("Raw_data.csv")

In [6]:
text_data.head()

,Unnamed: 0,text,url,name,department,text_len
0,1206,Too_Long:Over 20 Pages,['https://assets.nationbuilder.com/cuapb/pages...,"['Alexander Brown, badge #820', 'Alisa Clemons...","['Department:Champlin Police Department', 'Dep...",22
1,77,1336323 1336324 1336325,['https://assets.nationbuilder.com/cuapb/pages...,"['Michael Manley, badge #4385']",['Department:Minneapolis Police Department'],23
2,1395,https://minnesota.cbslocal.com/2018/07/25/poli...,['https://d3n8a8pro7vhmx.cloudfront.net/cuapb/...,"['Michael Zueg, badge #None']",['Department:Walnut Grove Police Department'],85
3,1394,https://minnesota.cbslocal.com/2018/06/21/kass...,['https://d3n8a8pro7vhmx.cloudfront.net/cuapb/...,"['Julio Baez, badge #None']",['Department:Kasson Police Department'],92
4,898,MR. DENNIS RODOLFO HERNANDEZ-ANTUNEZ 1147 N 7...,['https://d3n8a8pro7vhmx.cloudfront.net/cuapb/...,"['Christopher Steward, badge #6823', 'Patrick ...",['Department:Minneapolis Police Department'],100

In [10]:
text_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1413 non-null   int64
 1   text        1413 non-null   object
 2   url         1413 non-null   object
 3   name        1413 non-null   object
 4   department  1413 non-null   object
 5   text_len    1413 non-null   int64
dtypes: int64(2), object(4)
memory usage: 66.4+ KB

In [13]:
text_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1413 non-null   int64
 1   text        1413 non-null   object
 2   url         1413 non-null   object
 3   name        1413 non-null   object
 4   department  1413 non-null   object
 5   text_len    1413 non-null   int64
 6   url_list    1413 non-null   object
 7   url1        1413 non-null   object
dtypes: int64(2), object(6)
memory usage: 88.4+ KB

In [ ]:
#text_data["url"].astype(list)

TypeError: dtype '<class 'list'>' not understood

In [4]:
text_data["url1"] = (
    text_data["url"]
    .apply(lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None)
    .str.strip("'")
)

In [14]:
text_df=text_data[["url1", "text"]]

In [21]:
text_df=text_df.rename(columns={"url1":"url"})

In [22]:
text_df.head()

,url,text
0,https://assets.nationbuilder.com/cuapb/pages/2...,Too_Long:Over 20 Pages
1,https://assets.nationbuilder.com/cuapb/pages/1...,1336323 1336324 1336325
2,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,https://minnesota.cbslocal.com/2018/07/25/poli...
3,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,https://minnesota.cbslocal.com/2018/06/21/kass...
4,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,MR. DENNIS RODOLFO HERNANDEZ-ANTUNEZ 1147 N 7...

In [30]:
baserow_data=pd.read_csv("export - Round 1.csv")

In [36]:
baserow_data.tail()

,id,url,Volunteer ID,Text Type,Explanation if Other,Progress,Incident Mentioned,Incident Type,Incident Type is Clear/Unclear,Officer Involved In Incident,...,Location Found,Location,Inferred or Explicit Location?,Date of Incident,Time of Incident,Approximate Date or Time if No Exact Date or Time Given,Officer Age,Citizen Age,Volunteer Notes,Round 2
1408,1409,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,Enter your volunter # here,NaN,Leave blank otherwise,Not Started,NaN,NaN,NaN,Enter unknown if no officer identified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
1409,1410,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,CCRT,Legal Document,Lawsuit,Done,Yes,NaN,NaN,Enter unknown if no officer identified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
1410,1411,https://assets.nationbuilder.com/cuapb/pages/1...,CCRT,Legal Document,Lawsuit,Done,NaN,NaN,NaN,Enter unknown if no officer identified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://assets.nationbuilder.com/cuapb/pages/1...
1411,1412,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,Enter your volunter # here,NaN,Leave blank otherwise,Not Started,NaN,NaN,NaN,Enter unknown if no officer identified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
1412,1413,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,CCRT,Legal Document,Memorandum Opinion and Order,Done,NaN,NaN,NaN,Enter unknown if no officer identified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...

In [37]:
baserow_data_done=baserow_data[baserow_data["Progress"]!="Not Started"]

In [38]:
baserow_data_done.shape

(420, 24)

In [39]:
merged=pd.merge(baserow_data_done, text_df,on="url", how="left")

In [40]:
merged.shape

(420, 25)

In [29]:
baserow_data.shape

(112, 24)

In [18]:
baserow_data

,id,url,Volunteer ID,Progress,Text Type,Explanation if Other,Incident Mentioned,Incident Type,Incident Type is Clear/Unclear,Officer Involved In Incident,...,Citizen Race,Citizen Age,Location Found,Location,Inferred or Explicit Location?,Date of Incident,Time of Incident,Approximate Date or Time if No Exact Date or Time Given,Volunteer Notes,Round 2
0,4,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,HUNG,Done,News Article,Leave blank otherwise,Unsure,Other,Clear,Julio Baez,...,Not Mentioned,Under 13,NaN,Olmsted County and Dodge County,Location Required Inference,NaN,NaN,Beginning of 1992,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
1,7,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,HUNG,Done,News Article,Leave blank otherwise,Yes,Other,Clear,David Edward Campbell,...,Not Mentioned,NaN,Relative Location,La Quinta Inn on Nicollet Avenue near Intersta...,Location Required Inference,09/08/2017,NaN,"About 6 pm, Friday",NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
2,8,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,SUMS,Done,News Article,Leave blank otherwise,Yes,Excessive Force,Clear,Tyrone Barze Jr.,...,Not Mentioned,"22 , NA",Exact Address,Cub Foods at 701 W Broadway,Location Explicitly Stated,NaN,NaN,"7:30pm , Thursday",NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
3,9,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,HUME,Done,News Article,Leave blank otherwise,Yes,Other,Clear,Lindsay E. Anderson,...,Not Mentioned,NaN,Relative Location,"Columbia Heights, MN",Location Explicitly Stated,04/25/2006,NaN,NaN,Two officers arrested for driving under the in...,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
4,12,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,SUEP,Done,News Article,Leave blank otherwise,Yes,Lack of SOP,Clear,"Marvin Schumer, Michael Lardy",...,"Not Mentioned,American Indian or Alaska Native",Not Mentioned,Relative Location,Hennepin County Medical Center,Location Required Inference,NaN,NaN,Before Jun 14 1993,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,575,https://assets.nationbuilder.com/cuapb/pages/1...,CCEH,Done,News Article,NaN,Yes,Other,Unclear,Jeffrey Masek,...,Not Mentioned,NaN,Relative Location,Farm and Fleet,Location Explicitly Stated,04/28/2018,02/17/2026 12:00 AM,NaN,The officer was caught during an undercover op...,https://assets.nationbuilder.com/cuapb/pages/1...
108,606,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,CCEH,Done,News Article,Domestic assault,Yes,Other,Unclear,Myron Wieland,...,Not Mentioned,NaN,NaN,NaN,NaN,08/24/2015,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
109,658,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,CCEH,Done,News Article,Fatal vehicle collision,Yes,Other,Unclear,unknown,...,Not Mentioned,24,Exact Address,"Blaisdell and 26th, Minneapolis",Location Explicitly Stated,05/10/2013,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...
110,869,https://assets.nationbuilder.com/cuapb/pages/2...,CCEH,Done,News Article,NaN,No,NaN,NaN,Michael Keefe,...,Not Mentioned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://assets.nationbuilder.com/cuapb/pages/2...
111,1326,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...,SUJL,Done,News Article,Leave blank otherwise,Yes,"Verbal Abuse,Discrmination",Clear,"Roderic Weber, Dan Dietrich",...,Black or African American,17,Exact Address,"Pillsbury Ave, W 33rd St, South Minneapolis",Location Explicitly Stated,03/15/2015,NaN,NaN,NaN,https://d3n8a8pro7vhmx.cloudfront.net/cuapb/pa...

In [ ]:
OLLAMA_URL = "http://localhost:11434/api/generate" 

def call_ollama(prompt, model="mistral:latest"):
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    headers = {"Content-Type": "application/json"}

    response = requests.post(OLLAMA_URL, json=payload, headers=headers)
    response.raise_for_status()

    return response.json().get("response", "")

 The capital of France is Paris.

In [42]:
reply = call_ollama("What is 1 + 25")
print(reply)

 The sum of 1 and 25 is 26.

In [45]:
merged.to_csv("test_complete_set.csv")

In [46]:
testing=merged[["url", "text"]]

In [ ]:
%time call_ollama("Hello", model="mistral:latest")

In [1]:
testing.head()

NameError: name 'testing' is not defined

In [9]:
q=pd.read_csv("test_test_labeled.csv")

In [11]:
q.head()

   Unnamed: 0                                               text         label
0           0                                                NaN         Other
1           1                            1336323 1336324 1336325         Other
2           2  https://minnesota.cbslocal.com/2018/07/25/poli...  News Article
3           3  https://minnesota.cbslocal.com/2018/06/21/kass...  News Article
4           4  MR. DENNIS RODOLFO HERNANDEZ-ANTUNEZ  1147 N 7...         Other

In [8]:
v=pd.read_csv("test_complete_set.csv")

In [12]:
z=pd.merge(q,v, on="text", how="left")

In [14]:
z["Check"]=z["label"]==z["Text Type"]

In [16]:
z["Check"].value_counts()

Check
False    296
True     124
Name: count, dtype: int64

In [20]:
q["label"].value_counts()

label
News Article        284
Court Proceeding     55
Other                45
Police Document      36
Name: count, dtype: int64

In [21]:
v["Text Type"].value_counts()

Text Type
Legal Document          184
News Article            123
Police Dept Document     61
Other                    44
Name: count, dtype: int64